language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly"
install:
  - pip install -e .[testing,yaml]
script:
  - python setup.py test
  - make test
