[metadata]
name = jqfpy
version = file: VERSION
description = jq for pythonista
long_description = file: README.md, CHANGES.txt
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.5
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: PyPy
keywords = jq
author = podhmo
author_email = ababjam61+github@gmail.com
url = https://github.com/podhmo/jqfpy
license = MIT

[options]
packages = find_namespace:
package_dir =
    = .
include_package_data = True
zip_safe = False
install_requires =
    magicalimport
tests_require =
test_suite = jqfpy.tests

[options.packages.find]
exclude =
    jqfpy.tests*

[options.extras_require]
testing =
yaml =
    PyYAML
docs =
dev =
    black

[options.entry_points]
console_scripts =
    jqfpy = jqfpy.__main__:main

[bdist_wheel]